/*
 * Copyright (C) 2013 Justus Piater,
 * Intelligent and Interactive Systems Group,
 * University of Innsbruck, Austria.
 */
/*
 * This file is part of simple-cbir.
 *
 *  simple-cbir is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  simple-cbir is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with simple-cbir.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Diese Datei ist Teil von simple-cbir.
 *
 *  simple-cbir ist Freie Software: Sie können es unter den Bedingungen
 *  der GNU General Public License, wie von der Free Software Foundation,
 *  Version 3 der Lizenz oder (nach Ihrer Wahl) jeder späteren
 *  veröffentlichten Version, weiterverbreiten und/oder modifizieren.
 *
 *  simple-cbir wird in der Hoffnung, dass es nützlich sein wird, aber
 *  OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
 *  Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
 *  Siehe die GNU General Public License für weitere Details.
 *
 *  Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
 *  Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.
 */
package cbir.reader;

import java.io.File;
import java.util.Iterator;
import java.util.List;

import org.dom4j.DocumentException;

import cbir.image.DescriptorType;
import cbir.image.ImageContainer;

/**
 * A simple testing class for XML reader. "file" specifies the path of the XML
 * file (containing only MPEG-EHD & CEDD) generated by img(rummager). For
 * testing purposes.
 * 
 * @author Matej Stanic
 * 
 */
public class XMLReaderTest {

	public static void main(String[] args) {
		// Parse given XML file
		XMLReader reader = new XMLReader();
		File file = new File("C:\\MBOX\\signed_all\\corel_ehd_cedd.xml");
		try {
			reader.parseXMLFile(file);
		} catch (DocumentException e) {
			e.printStackTrace();
		}
		// get list of parsed images
		List<ImageContainer> imageList = reader.getImageList();
		// print list
		System.out.println("test");
		Iterator<ImageContainer> it = imageList.iterator();
		while (it.hasNext()) {
			ImageContainer temp = it.next();
			System.out.println("Image: " + temp.getFilename());
			double[] edgeHisto = temp.getDescriptor(DescriptorType.MPEG_EHD)
					.getValues();
			double[] cedd = temp.getDescriptor(DescriptorType.CEDD).getValues();
			System.out.print("EHD: ");
			for (int i = 0; i < edgeHisto.length; i++)
				System.out.print(edgeHisto[i] + " ");
			System.out.println();
			System.out.print("CEDD: ");
			for (int i = 0; i < cedd.length; i++)
				System.out.print(cedd[i] + " ");
			System.out.println();
		}
		System.out.println("total: " + imageList.size());
	}
}
